config/routes.rb
Rails.application.routes.draw do
  root 'sessions#home'
  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'
  get 'sessions/new', to: 'users#show'
  
  resources :users, only: [:new, :create, :show, :edit]
  
  get '/profile', to: 'users#show'
  get '/profile/edit', to: 'users#edit'
  patch '/profile', to: 'users#update'
  get 'dogs/:id/edit', to: 'dogs#edit', as: 'edit'


  resources :dogs, only: [:new, :create, :destroy, :index, :show, :update]
  patch '/dogs/:id/adopt', to: 'dogs#adopt', as: 'adopt'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
    has_attached_file :image, styles: { :thumb => "100x100", :small  => "150x150", :medium => "200x200" }, presence: true
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

    scope :adopted, -> {where.not(adoptor_id: nil)}
    scope :not_adopted, -> {where(adoptor_id: nil)}

    belongs_to :user
    belongs_to :adoptor, class_name: 'User', optional: true
end

app/models/user.rb
class User < ApplicationRecord
    has_attached_file :image, styles: { small: "250x250>", thumb: "250x250>" }, presence: true
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    has_secure_password
    validates :email, presence: true, uniqueness: true 

    has_one :dog
    has_many :dogs, class_name: 'Dog', foreign_key: :adoptor_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id] 
  end

  def current_user_params
    params.require(:current_user).permit(:name, :email, :password, :password_confirmation)
  end

  def authorize
    redirect_to new_user_path unless current_user
  end
  
  
  private

    helper_method :current_user



end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  
  before_action :authorize


  def index
    @dogs = Dog.all
  end
  
  
  def new
    @dog = Dog.new
  end

  
  def create
    @dog = Dog.new(user_params)
    @dog.user = current_user
    if @dog.save
      flash[:notice] = "You have successfully signed up your dog!"
      redirect_to dogs_path
    else
      render :new
    end
  end

  def edit
    @dog = Dog.find(params[:id])
  end

  def update
    @dog = Dog.find(params[:id])
    if @dog.update_attributes(user_params)
      redirect_to dogs_path
    else
      render :edit
    end
  end

  def destroy
    @dog = Dog.find(params[:id])
    if current_user == Dog.find(params[:id]).user
    @dog.destroy
    redirect_to dogs_path
    end
  end

  def show
    @dog = Dog.find(params[:id])
  end


  def adopt
    Dog.find(params[:id]).update_attributes(adoptor: current_user)
    redirect_to dog_path(params[:id])
  end



    private
  
     
      def user_params
        params.require(:dog).permit(:name, :pound_location, :age, :description, :image, :phone_number)
      end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
     def new
        # Nothing to do here other than render new.html.erb
      end
  
     def home
      if current_user then redirect_to dogs_path
      end
    end
     
    def create
        # Not using an instance variable since
        # we're not providing the user to a view
        user = User.find_by(email: params[:email])
        # Taking advantage of the && logical operator's
        # short-circuiting
        if user && user.authenticate(params[:password])
          # Successful log in!
          session[:user_id] = user.id
          # notice: is a special flash[:notice] accessor
  
         # TODO: if user.teacher, then redirect to lessons index
          redirect_to dogs_path, notice: 'Logged in!'
        else
          # flash.now is used for messaging
          # during the CURRENT request
          flash.now.alert = 'Invalid login credentials - try again!'
          render :new
        end
      end

     def destroy
        session[:user_id] = nil
        redirect_to root_path, 'notice': "Logged out!"
      end
    
   end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    # Provide the model instance to the form_for helper
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You have successfully signed up!"
      redirect_to login_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

 

  private

   
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :description, :location, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dogs/edit.html.erb
<div id=dogs>
   <h1>Dog Admissions</h1>
   <%= form_for @dog do |d| %>
   <% if @dog.errors.any? %>
   <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
         <% for message in @dog.errors.full_messages %>
         <li><%= message %></li>
         <% end %>
      </ul>
   </div>
   <% end %>
   <div class="field">
      <%= d.label :name %><br>
      <%= d.text_field :name %>
   </div>
   <div class="field">
      <%= d.label :pound_location %><br>
      <%= d.text_field :pound_location %>
   </div>
   <div class="field">
      <%= d.label :phone_number %><br>
      <%= d.text_field :phone_number %>
   </div>
   <div class="field">
      <%= d.label :age %><br>
      <%= d.number_field :age %>
   </div>
   <div class="field">
      <%=d.label :description%><br>
      <%=d.text_field :description%>
   </div>
   <div class="field">
      <%= d.label :image %><br>
      <%= d.file_field :image %>
   </div>
   <div class="actions"><%= d.submit %></div>
   <% end %>
</div>

app/views/dogs/index.html.erb
<div id="dogs">
   <h1>Welcome to the Dogs</h1>
   <h2>Looking for a new home for your pup? <br> <br> Begin <%= link_to 'Here', new_dog_path %></h2>
   <br>
</div>
<div class="dogelist">
   <ul>
      <% @dogs.each do |d| %>
      <% if d.adoptor.nil? %>
      <li>
         <p id="img"><%= image_tag(d.image) %> </p>
         <p><%=d.name%></p>
         <p><%= "#{d.age} years old" %> </p>
         <p><%= d.pound_location %></p>
         <% if d.user.id == current_user.id %>
         <%= link_to "Delete", dog_path(d), :method => :delete %>
         <%= link_to "Edit", edit_path(d) %>
         <% end %>
         <p><%= link_to 'Adopt!', adopt_path(d), method: :patch %></p>
      </li>
      <% end %>
      <% end %>
   </ul>
</div>

app/views/dogs/new.html.erb
<div id=dogs>
   <h1>Dog Admissions</h1>
   <%= form_for @dog do |d| %>
   <% if @dog.errors.any? %>
   <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
         <% for message in @dog.errors.full_messages %>
         <li><%= message %></li>
         <% end %>
      </ul>
   </div>
   <% end %>
   <div class="field">
      <%= d.label :name %><br>
      <%= d.text_field :name %>
   </div>
   <div class="field">
      <%= d.label :pound_location %><br>
      <%= d.text_field :pound_location %>
   </div>
   <div class="field">
      <%= d.label :phone_number %><br>
      <%= d.text_field :phone_number %>
   </div>
   <div class="field">
      <%= d.label :age %><br>
      <%= d.number_field :age %>
   </div>
   <div class="field">
      <%=d.label :description%><br>
      <%=d.text_field :description%>
   </div>
   <div class="field">
      <%= d.label :image %><br>
      <%= d.file_field :image %>
   </div>
   <div class="actions"><%= d.submit %></div>
   <% end %>
</div>

app/views/dogs/show.html.erb
<h1>Thank you, <%= @dog.adoptor.name %>, for saving <%= @dog.name %>!</h1>
<div class="dogelist">
   <ul>
      <li>
         <p id="img"><%= image_tag(@dog.image) %> </p>
         <p> <%= @dog.name %> </p>
         <p> <%= @dog.description %> </p>
         <p> <%= "#{@dog.age} years old" %> </p>
         <p> <%= "Pick up your new furry friend at the #{@dog.pound_location} pound" %> </p>
         <p> <%= @dog.phone_number %> </p>
         <p><%= link_to 'Want to save more doggies?!', dogs_path %></p>
      </li>
   </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
      <title>DogWhisperer</title>
      <%= csrf_meta_tags %>
      <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      <script
         src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
         integrity="sha256-k2WSCIexGzOj3Euiig+TlR8gA0EmPjuc79OEeY5L45g="
         crossorigin="anonymous"></script>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   </head>
   <body>
      <div class="navbar navbar-default">
         <div class="container-fluid">
            <div class="navbar-header">
               <button type="button" 
                  class="navbar-toggle"
                  data-toggle="collapse" 
                  data-target="#mynavbar-content">
               <span  class="icon-bar"></span>
               <span  class="icon-bar"></span>
               <span  class="icon-bar"></span>
               </button>
               <a class="navbar-brand" href=<%=dogs_path%>>DogWhsprr</a>
            </div>
            <% if current_user %>
            Welcome, <%= current_user.name %>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <%= link_to 'Log Out', session_path('logged'), method: :delete %>
            <% else %>
            <%= link_to 'Log In', login_path %>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <%= link_to 'Sign Up', new_user_path %>
            <% end %>
            <div class="collapse navbar-collapse" id="mynavbar-content">
               <ul class="nav navbar-nav">
                  <li><a href=<%=dogs_path%>>Home</a></li>
                  <% unless current_user %>
                  <li><a  href=<%=new_user_path%>>Sign Up</a></li>
                  <% end %>
                  <li><a  href=<%=dogs_path%>>Check Em Out</a></li>
                  <% if current_user %>
                  <li><a  href=<%= user_path(current_user.id) %>>Your Profile</a></li>
                  <% end %>
               </ul>
            </div>
         </div>
      </div>
      <%= yield %>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
   </body>
</html>

app/views/users/edit.html.erb
<div id="content">
   <h1>Sign Up</h1>
   <div class="row">
      <div class="col-6 col-md-4">
         <a href=<%=login_path%>>Already a User?</a>
      </div>
      <div class="col-6 col-md-4">
         <%= form_for @user do |f| %>
         <% if @user.errors.any? %>
         <div class="error_messages">
            <h2>Form is invalid</h2>
            <ul>
               <% for message in @user.errors.full_messages %>
               <li><%= message %></li>
               <% end %>
            </ul>
         </div>
         <% end %>
         <div class="field">
            <%= f.label :name %>
            <%= f.text_field :name %>
         </div>
         <div class="field">
            <%= f.label :email %>
            <%= f.text_field :email %>
         </div>
         <div class="field">
            <%= f.label :location %>
            <%= f.text_field :location %>
         </div>
         <div class="field">
            <%= f.label :description %>
            <%= f.text_field :description %>
         </div>
         <div class="field">
            <%= f.label :password %>
            <%= f.password_field :password %>
         </div>
         <div class="field">
            <%= f.label :confirm_password %>
            <%= f.password_field :password_confirmation %>
         </div>
         <div class="field">
            <%= f.label :image %><br>
            <%= f.file_field :image %>
         </div>
         <div class="actions"><%= f.submit %></div>
         <% end %>
      </div>
   </div>
</div>

app/views/users/new.html.erb
<div id="content">

<h1>Sign Up</h1>

<div class="row">

  <div class="col-6 col-md-4">
    <a href=<%=login_path%>>Already a User?</a>
  </div>

  <div class="col-6 col-md-4">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
      <div class="field">
        <%= f.label :location %>
        <%= f.text_field :location %>
      </div>
      <div class="field">
        <%= f.label :description %>
        <%= f.text_field :description %>
      </div> 
      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <div class="field">
        <%= f.label :confirm_password %>
        <%= f.password_field :password_confirmation %>
      </div>
      <div class="field">
        <%= f.label :image %><br>
        <%= f.file_field :image %>
      </div>
      <div class="actions"><%= f.submit %></div>
    <% end %>
  </div>
  
</div>
</div>

app/views/users/show.html.erb
<h1>Hello, <%= @user.name %> </h1>
<div class="dogelist">
   <ul>
      <li>
         <p id="img"><%= image_tag(@user.image) %> </p>
         <p> <%= @user.description %> </p>
         <p> <%= @user.location %> </p>
         <p> <%= @user.email %> </p>
         <p> <%= link_to "Edit", edit_user_path %> </p>
      </li>
   </ul>
</div>